version: '3'

services:
  server:
    build: server/
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: node ./dist/main.js
    env_file: .env

  client:
    build: client/
    command: node ./server.cjs
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    depends_on:
      - server
    env_file: .env
