version: '3'

services:
  server:
    build: .
    ports:
      - 3001:3001
    command: node ./dist/main.js
    env_file:
      - ./server/.env

  client:
    build: client/
    command: node ./server.cjs
    ports:
      - 3000:3000
    depends_on:
      - server
    env_file:
      - ./server/.env
